### PR TITLE
Round stat numbers

### PR DESCRIPTION
**Pull request by vtyagunov**
Adding two ways to approach rounding of stat numbers.

1) Present every stat number with a fixed decimal fractional digit, using `.toFixed(2)`.
Examples: `0` -> `0.00`, `12` -> `12.00`, `15.000003` -> `15.00`, `45.35` -> `45.35`

2) Round the stats omitting trailing fractional digits, using `Intl.NumberFormat` Browser API
Examples: `0` -> `0`, `12` -> `12`, `15.000003` -> `15`, `45.35` -> `45.35`

Here is a screenshot for comparison:
On the left - Crit Rate and Crit DMG formatted with `Intl.NumberFormat`.
On the right - Crit Rate and Crit DMG formatted with `.toFixed(2)`.
image

### CODE REVIEW

**Comment by vtyagunov** [comment]
Hi @ryanbenson 

Let me know which way is preferable.
If it is ok, I can apply formatting for the rest of the stats.

**Comment by ryanbenson** [comment]
Your comment and idea here sounds good!

> Maybe CRate, CDamage, Energy Regen and other Bonuses can be formatted be like exactly like in the game - dd.d %. Having always 1 decimal.
> And all the rotations / dmg calculation - no decimals. rounding to integers

Edit: maybe not rounding is better. That may confuse people if we round up/down and it might not be what the game has. Maybe your simplified version is better to just use the number formatter

**Comment by vtyagunov** [comment]
Hi @ryanbenson 
I've added `displayPercentrage` function to format Crit, bonus and resistance based stats (basically, everything that is showed with % in the game). Numbers are formatted to `dd.d%` style with the floor rounding mode.

**Comment by ryanbenson** [comment]
@vtyagunov thanks! The percentages are looking great! Should we do anything to the totalAtk / totalDef / totalHp? I think they can still end up with long decimals like `889.9200000000001` (Jinshi lvl 90, using Autumtrace R1 with 2 stacks of the weapon passive will trigger it)

Not sure why I didn't get notified of your comment. I need to check my notification settings

**Comment by ryanbenson** [comment]
@vtyagunov I suppose we can just merge what you have and we can patch the last part of it later. There's a merge conflict, but I can help resolve that if you want

**Comment by ryanbenson** [comment]
Going to go ahead and merge this :) I Fixed the merge conflict. Thanks again for fixing this! 🎉

**Pull request merged**
